" basic stuff
syntax on
filetype plugin on
filetype indent on

" standard settings
set t_Co=256
set tabstop=4
set shiftwidth=4
set softtabstop=4
set backspace=2
set background=dark
set cursorcolumn
set cursorline
set expandtab
set number

"GUI options
set guioptions-=m "remove menu bar"
set guioptions-=T "remove toolbar"
set guioptions-=r "remove right-hand scroll bar"
set guioptions-=L "remove left-hand scroll bar"

" load in all plugins using pathogen
execute pathogen#infect()

" set nerdtree toggle
map <C-e> :NERDTreeToggle<CR>

" remap window navigation
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" syntastic std behaviour
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list            = 1
let g:syntastic_check_on_open            = 1
let g:syntastic_check_on_wq              = 0

" syntastic lang specific setup
let g:syntastic_javascript_checkers = [ 'eslint' ]
let g:syntastic_haskell_checkers    = [ 'hdevtools' ]
let g:syntastic_python_checkers     = [ 'mypy', 'flake8' ]
let g:syntastic_python_mypy_args    = '--ignore-missing-imports'
let g:syntastic_python_flake8_args  = '--ignore=E401,E221,E201,E251,E302,E202,E501,E203'
let g:syntastic_mode_map = { 'mode' : 'active', 'passive_filetypes' : [ '.jsx' ] }

" ignore file types in NERDTree explorer
let NERDTreeIgnore = [ '\.sock$', '\.pyc$', '\.o$', '\.hi$' ]

" m'color scheme
color gruvbox
